### ISSUE TITLE
gridSlider.js 404 not found - Banner is not working

### ISSUE THREAD

**Issue by arun-ameex** [magiccart/magento-2-banner-slider#1]
Hi Team,

We get 404 error gridSlider.js. It is called in magicslider.phtml. But js file is not in web js folder.
Kindly advise how to fix this issue?

Thanks
![error](https://user-images.githubusercontent.com/58293981/109529838-1645d080-7adc-11eb-8635-e3ac612b0a05.png)

**Comment by magiccart** [comment]
The gridSlider.js in this module https://github.com/magiccart/module-community. If you install via composer this depend auto installed. If you install manually please install module module-community to your site. The error above will auto fixed.

**Comment by arun-ameex** [comment]
Yes, It is working. Thanks Team
